### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Tim-Abwao**
## Description

* Use check-boxes in the endpoints section to show which work: 
 
  I'm relatively new to Django. I followed the installation guide and ran the server, but couldn't access most of the endpoints. Check-boxes can help identify which endpoints work and which might need to be fixed.
* Add details to installation guide.
* Fix grammar and a few typos.
* Update links with 'Team-Rio-Django' to 'mastori'.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

[CI Django & Postgres Tests](https://github.com/SpaceyaTech/blog/actions/workflows/django-postgres-ci.yml)

[Jambo](https://github.com/SpaceyaTech/mastori/actions/workflows/jambo.yaml)

**Test Configuration**:

    python manage.py migrate
    python manage.py test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by JimmyTron — APPROVED** [review]

**Review by JimmyTron — CHANGES_REQUESTED** [review]
Pull the recent changes first

**Comment by Tim-Abwao** [comment]
Done. I've rebased my changes on the recent changes in 890897b.

**Review by weshy007 — APPROVED** [review]

**Comment by JimmyTron** [comment]
image
I appreciate the changes that you recommend but you are undoing some changes that took me time to come up with more so on the formatting of the endpoints. Sijui how we could hit middle ground.

**Comment by JimmyTron** [comment]
> It's not right to quote the code as SQL when its not... image

Sure its not sql code but on markdown various snipets are formatted differently and chosing a language's markdown formating doesn't mean your code is.  it is similar with installing fonts or themes on your ide...

**Comment by Tim-Abwao** [comment]
Shifting focus back to Data Analysis & Data Science projects.

Had wished to get conversant with the Django framework. This project inspired me do so, thanks.

**Pull request closed without merging**
