### PR TITLE
Add Poetry config files for improved dependency management

### PR DESCRIPTION
**Pull request by tony-nyagah**
# Description

Added a pyproject.tml file using Poetry to the project. The file contains all the current project dependencies but using Poetry enables better management of dependencies preventing issues with circular dependency and invalid dependencies.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

[CI Django & Postgres Tests](https://github.com/SpaceyaTech/blog/actions/workflows/django-postgres-ci.yml)

[Jambo](https://github.com/SpaceyaTech/mastori/actions/workflows/jambo.yaml)

**Test Configuration**:

```sql
          python manage.py migrate
          python manage.py test
```

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Gibson-Gichuru** [comment]
Awesome! 
NIT: you can remove black from the production dependencies listing.

**Review by Gibson-Gichuru — CHANGES_REQUESTED** [review]
The docker images need to be updated to cater for the new dependency management

**Comment by tony-nyagah** [comment]
@Gibson-Gichuru I updated the requirements file. Exported the requirements from the pyproject.toml file. This should fix the error with the workflows.

**Comment by tony-nyagah** [comment]
> > @Gibson-Gichuru I updated the requirements file. Exported the requirements from the pyproject.toml file. This should fix the error with the workflows.
> 
> I mean the docker file still uses the old requirements.txt to build the application. should now be using the .tml file

This means the project is moving away from using the requirements.txt file to Poetry and the pyproject.toml file right?
I had assumed this issue was for keeping the requirements.txt file well updated.

**Review by JimmyTron — CHANGES_REQUESTED** [review]
I would recommend using Pipenv

**Comment by aibunny** [comment]
let's use pipenv for uniformity across all our python projects

**Comment by tony-nyagah** [comment]
> let's use pipenv for uniformity across all our python projects

Let me create an issue and get working on it.

**Pull request closed without merging**
